"""table posts (001)

Revision ID: 738e64986e4f
Revises: 9dac0fd85ee1
Create Date: 2020-04-20 08:08:31.645707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '738e64986e4f'
down_revision = '9dac0fd85ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.add_column('categories', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'categories', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'post_id')
    op.drop_table('posts')
    # ### end Alembic commands ###
